kind: Deployment
apiVersion: apps/v1
metadata:
   name: nginx-deployments
spec:
   replicas: 1
   selector:
    matchLabels:
     app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
      containers:
        - name: nginx
          image: nginx:1.14.1
          ports:
          - containerPort: 80
          
          
          
---
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80                               # Containers port exposed
      nodePort: 30275                   # Pods port
  selector:
    app: nginx                          # Apply this service to any pods which has the specific label


